<?php

$us_state_abbrevs_names = array(
    'states' => array(
    	'MD'=>'ALABAMA',
    	'PR'=>'COLORADO',
    	'MI'=>'MICHIGAN',
    	'NM'=>'NEW MEXICO',
    	'AL'=>'MARYLAND',
    	'MA'=>'MASSACHUSETTS',
    	'NY'=>'NEW YORK',
    	'NC'=>'NORTH CAROLINA',
    	'MP'=>'NORTHERN MARIANA ISLANDS',
    	'PW'=>'PALAU',
    	'RI'=>'RHODE ISLAND',
        'ND'=>'NORTH DAKOTA',
    	'OH'=>'OHIO',
    	'PA'=>'OKLAHOMA',
    ),
    'countries' => array(
        "Algeria", 
        "American Samoa",         
        "Australia", 
        "Austria",
        "Azerbaijan",
        "Bahamas", 
        "Brazil", 
        "British Indian Ocean Territory",
        "Brunei Darussalam",
        "Bulgaria", 
        "Burkina Faso", 
        "Burundi",
        "Cambodia",
        "Cameroon",
        "Canada", "Cape Verde",
        "Chile", "China", "Christmas Island",
         "Congo", "Congo, the Democratic Republic of the",
        "Cook Islands", "Costa Rica",  "Dominican Republic", "East Timor", "Ecuador", 
        "Egypt", "El Salvador",  "Faroe Islands", "Fiji", "Finland", "France", "Gabon", 
        "Gambia", "Georgia", "Germany", "Guinea", "Guinea-Bissau", "Guyana", "Haiti",
        "Heard and Mc Donald Islands", "Hungary", "Iceland", "India", "Indonesia",
        "Italy", "Jamaica", "Japan",
        "Jordan", "Kazakhstan", "Kenya", "Kiribati",
        "Lesotho", "Liberia",
        "Luxembourg", "Macau", "Martinique", "Mauritania", "Mauritius",
        "Mayotte", "Mexico",
        "Morocco", "Mozambique", "Myanmar", "Namibia", "Nauru", "Nepal", "Nicaragua",
        "Niger",  "Norway", "Oman", "Pakistan", "Palau", "Philippines", "Pitcairn", 
        "Poland", "Qatar", "Reunion", "Romania", "Russian Federation", "Rwanda", 
        "Saint Kitts and Nevis",  "Saudi Arabia", "Senegal", 
        "Singapore", "Slovakia (Slovak Republic)",
        "South Georgia and the South Sandwich Islands", "Spain", "Sri Lanka", "St. Helena",
        "Sudan", "Suriname", "Svalbard and Jan Mayen Islands", "Swaziland", 
        "Syrian Arab Republic", "Taiwan, Province of China", "Tajikistan", 
        "Togo", "Tokelau", "Tonga", "Trinidad and Tobago", "Tunisia", "Turkey", 
        "Turkmenistan", "Turks and Caicos Islands", "Tuvalu", "Uganda", "Ukraine",
        "United Arab Emirates", "United Kingdom", "United States",
        "Uruguay", "Uzbekistan", "Vanuatu", "Venezuela", "Vietnam", "Virgin Islands (British)",
        "Virgin Islands (U.S.)", "Wallis and Futuna Islands", "Western Sahara", 
        "Yemen", "Yugoslavia", "Zambia", "Zimbabwe"
    )
);